'use strict';
/* Rin Harbor warehouse extension. Loaded after game.js so existing saves/game rules remain compatible. */
(()=>{
  const WAREHOUSE_BASE=12;
  if(!S.warehouse||typeof S.warehouse!=='object')S.warehouse={};
  const originalNormalize=normalize;
  normalize=function(raw){const wh=raw&&typeof raw.warehouse==='object'?raw.warehouse:{};originalNormalize(raw);S.warehouse={};for(const [id,n] of Object.entries(wh)){const count=int(n,0,999,0);if(count&&hasItem(id)&&!isGen(id))S.warehouse[id]=count}};
  const originalFresh=freshState;freshState=function(){const state=originalFresh();state.warehouse={};return state};
  const used=()=>Object.values(S.warehouse||{}).reduce((a,n)=>a+int(n,0,999,0),0);
  const capacity=()=>WAREHOUSE_BASE+S.repair*4+Math.floor(Math.max(0,S.level-1)/3)*2;
  const free=()=>Math.max(0,capacity()-used());
  const entries=()=>Object.entries(S.warehouse||{}).filter(([id,n])=>hasItem(id)&&!isGen(id)&&n>0).sort((a,b)=>ITEMS[a[0]].k.localeCompare(ITEMS[b[0]].k)||levelOf(a[0])-levelOf(b[0]));
  function inject(){
    if(document.getElementById('screenWarehouse'))return;
    document.getElementById('screenBook').insertAdjacentHTML('beforebegin',`<section id="screenWarehouse" class="screen"><header class="card"><div class="top"><div><span class="eyebrow">あとで使う材料を、ここで保管</span><div class="title">みなとの倉庫</div><div id="warehouseLead" class="sub"></div></div><button data-go="game" class="primary">盤面へ戻る</button></div><div id="statsWarehouse" class="stats"></div></header><div class="card"><div class="top"><div><h2>倉庫のようす</h2><div class="sub">リン号の修理とレベルが進むと、容量も少し増えます。</div></div><span id="warehouseCount" class="pill">0/0</span></div><div class="warehouseMeter"><i id="warehouseMeterBar"></i></div><div class="warehouseMeta"><span id="warehouseUsage"></span><span id="warehouseBoard"></span></div></div><div class="card"><h2>しまっているアイテム</h2><div id="warehouseList" class="warehouseList"></div></div></section>`);
    document.querySelector('.homeGrid').insertAdjacentHTML('beforeend',`<button class="menuCard warehouseMenu" data-go="warehouse"><span class="menuIcon"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 7.5 12 4l8 3.5v9L12 20l-8-3.5v-9Z"/><path d="M4 7.5 12 11l8-3.5"/><path d="M12 11v9"/></svg></span><b>みなとの倉庫</b><span id="homeWarehouseSub" class="tiny">0/0 保管中</span></button>`);
    document.querySelector('#nav [data-go="book"]').insertAdjacentHTML('beforebegin',`<button data-go="warehouse"><span class="navIcon"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 7.5 12 4l8 3.5v9L12 20l-8-3.5v-9Z"/><path d="M4 7.5 12 11l8-3.5"/><path d="M12 11v9"/></svg></span>倉庫</button>`);
    document.getElementById('sell').insertAdjacentHTML('afterend','<button id="store" class="warn" disabled>倉庫へ</button>');
    document.head.insertAdjacentHTML('beforeend',`<style id="warehouseStyles">.homeGrid{grid-template-columns:repeat(2,minmax(0,1fr))}.warehouseMenu .menuIcon{color:#b36b51}.nav{grid-template-columns:repeat(6,minmax(0,1fr))}.controls{grid-template-columns:repeat(7,minmax(0,1fr))}.warehouseMeter{height:12px;background:#e6eee7;border-radius:999px;overflow:hidden;margin-top:12px}.warehouseMeter i{display:block;height:100%;background:linear-gradient(90deg,#168d8b,#e5b862);border-radius:inherit}.warehouseMeta{display:flex;justify-content:space-between;gap:8px;flex-wrap:wrap;margin-top:8px;font-size:11px;color:#607d78}.warehouseList{display:grid;gap:10px}.warehouseItem{padding:12px;border:1px solid #dce7dd;border-radius:16px;background:#fffef9}.warehouseTop{display:flex;align-items:center;gap:11px}.warehouseArt{width:58px;height:58px;display:grid;place-items:center;background:#f2f7ef;border:1px solid #d7e4d8;border-radius:14px;flex:none}.warehouseArt .itemArt{width:48px;height:48px}.warehouseInfo{flex:1;min-width:0}.warehouseInfo b{display:block;font-size:14px}.warehouseInfo small{display:block;color:#6d8580;margin-top:2px}.warehouseNum{font-weight:850;color:#51716b;background:#edf4ed;border-radius:999px;padding:5px 9px}.warehouseActions{text-align:right;margin-top:8px}.warehouseEmpty{padding:20px 12px;border:1px dashed #cfdcd1;border-radius:15px;color:#66807a;line-height:1.7;background:#fbfdf8}.bookItem{position:relative}.bookItem:not(.locked)::after{content:attr(data-rank);position:absolute;top:3px;right:3px;font-size:8px;font-weight:900;color:#fff;background:#3c817b;border-radius:999px;min-width:18px;height:18px;display:grid;place-items:center;border:2px solid #fff}@media(min-width:700px){.homeGrid{grid-template-columns:repeat(4,minmax(0,1fr))}}@media(max-width:360px){.controls{grid-template-columns:repeat(4,minmax(0,1fr))}}@media(orientation:landscape) and (max-height:540px){.nav{grid-template-rows:repeat(6,1fr)}}</style>`);
  }
  function storeSelected(){if(selected===null){say('倉庫にしまうアイテムを選んでね。');return}const id=S.board[selected];if(!id||isGen(id)){say('屋台は倉庫にはしまえないよ。');return}if(free()<1){toast('倉庫がいっぱいです。先に何か取り出してね。');return}makeUndo('倉庫へ保管');S.board[selected]=null;S.warehouse[id]=(S.warehouse[id]||0)+1;selected=null;hintPair=[];restoreGenerators();renderAll();saveNow();say(`${nameOf(id)} を倉庫へしまったよ。`);toast('倉庫にしまいました')}
  function take(id){if(!hasItem(id)||isGen(id)||!S.warehouse[id])return;const spaces=emptyCells();if(!spaces.length){toast('盤面に空きがありません。先に合成か納品をしてね。');return}makeUndo('倉庫から取り出す');const pos=spaces[0];S.board[pos]=id;S.book[id]=1;S.warehouse[id]--;if(S.warehouse[id]<=0)delete S.warehouse[id];selected=pos;renderAll();saveNow();toast(`${nameOf(id)} を盤面に戻しました`)}
  function renderWarehouse(){const u=used(),cap=capacity(),space=emptyCells().length;document.getElementById('statsWarehouse').innerHTML=statsHtml();document.getElementById('warehouseCount').textContent=`${u}/${cap}`;document.getElementById('warehouseUsage').textContent=`${u}/${cap} 使用中`;document.getElementById('warehouseBoard').textContent=`盤面の空き ${space}マス`;document.getElementById('warehouseMeterBar').style.width=Math.min(100,u/cap*100)+'%';document.getElementById('warehouseLead').textContent=u?'空きマスがあれば、いつでも盤面に戻せます。':'ゲーム画面でアイテムを選び「倉庫へ」を押すと保管できます。';const list=document.getElementById('warehouseList'),data=entries();list.innerHTML=data.length?data.map(([id,n])=>`<div class="warehouseItem"><div class="warehouseTop"><div class="warehouseArt">${itemArt(id)}</div><div class="warehouseInfo"><b>${esc(nameOf(id))}</b><small>${esc(CHAIN_DATA[ITEMS[id].k].label)} ・ Lv${levelOf(id)}</small></div><span class="warehouseNum">×${n}</span></div><div class="warehouseActions"><button class="good" data-warehouse-take="${id}" ${space?'':'disabled'}>取り出す</button></div></div>`).join(''):'<div class="warehouseEmpty">まだ倉庫は空っぽです。<br>盤面がいっぱいになる前に、あとで使うアイテムをしまっておこう。</div>'}
  inject();
  const oldSetView=setView;setView=function(v){if(v==='warehouse'){cancelDrag();view=v;document.body.dataset.view=v;selected=null;hintPair=[];document.querySelectorAll('.screen').forEach(x=>x.classList.remove('on'));document.getElementById('screenWarehouse').classList.add('on');document.getElementById('nav').classList.remove('hidden');document.querySelectorAll('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.go===v));renderWarehouse();document.getElementById('screenWarehouse').scrollTop=0;return}oldSetView(v)};
  const oldRenderAll=renderAll;renderAll=function(){oldRenderAll();const sub=document.getElementById('homeWarehouseSub');if(sub)sub.textContent=`${used()}/${capacity()} 保管中`;if(view==='warehouse')renderWarehouse()};
  const oldRenderGame=renderGame;renderGame=function(){oldRenderGame();const b=document.getElementById('store');if(b)b.disabled=selected===null||!S.board[selected]||isGen(S.board[selected])||free()<1};
  const oldRenderBook=renderBook;renderBook=function(){oldRenderBook();document.querySelectorAll('#bookChains .bookItem:not(.locked)').forEach(el=>{const txt=el.querySelector('.bookLv')?.textContent||'';el.dataset.rank=txt.replace('Lv','L')})};
  document.getElementById('store').addEventListener('click',storeSelected);document.body.addEventListener('click',e=>{const b=e.target.closest('[data-warehouse-take]');if(b&&!b.disabled)take(b.dataset.warehouseTake)});renderAll();saveSoon();
})();
